services:
  - type: web
    name: snake-game
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./build/web
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /*.js
        name: Content-Type
        value: application/javascript